[bug fix] Script will exhaust available file descriptors
When creating temp files with `tempfile.mkstemp()`, the first element
of the returned tuple is an OS file descriptor. The file needs to be
explicitly closed with `os.close(fd)`, otherwise the script will
crash (tipically after opening 1024 files) with:

    IOError: [Errno 24] Too many open files: